import os
from datetime import datetime


class ReportGenerator:

    def __init__(self, database):

        self.database = database

        self.report_folder = "reports"

        os.makedirs(
            self.report_folder,
            exist_ok=True
        )

    # =====================================================
    # GENERATE HTML REPORT
    # =====================================================

    def generate_html_report(self):

        alerts = self.database.get_alerts()

        report_time = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        total_alerts = len(alerts)

        high_count = 0
        medium_count = 0
        low_count = 0

        for alert in alerts:

            risk = str(alert[4]).upper()

            if risk == "HIGH":
                high_count += 1

            elif risk == "MEDIUM":
                medium_count += 1

            elif risk == "LOW":
                low_count += 1

        rows = ""

        for alert in alerts:

            alert_id = alert[0]
            timestamp = alert[1]
            alert_type = alert[2]
            source_ip = alert[3]
            risk = alert[4]
            message = alert[5]

            rows += f"""
            <tr>
                <td>{alert_id}</td>
                <td>{timestamp}</td>
                <td>{alert_type}</td>
                <td>{source_ip}</td>
                <td>{risk}</td>
                <td>{message}</td>
            </tr>
            """

        if not rows:

            rows = """
            <tr>
                <td colspan="6">
                    No security alerts recorded.
                </td>
            </tr>
            """

        html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>NIDS Security Report</title>

<style>

body {{
    font-family: Arial, sans-serif;
    background: #f3f4f6;
    margin: 0;
    padding: 30px;
}}

.container {{
    max-width: 1200px;
    margin: auto;
    background: white;
    padding: 30px;
    border-radius: 10px;
}}

h1 {{
    color: #111827;
}}

.subtitle {{
    color: #6b7280;
}}

.dashboard {{
    display: flex;
    gap: 15px;
    margin: 25px 0;
}}

.card {{
    flex: 1;
    padding: 20px;
    border-radius: 8px;
    background: #f9fafb;
    text-align: center;
}}

.card h2 {{
    margin: 5px;
}}

.high {{
    color: #dc2626;
}}

.medium {{
    color: #d97706;
}}

.low {{
    color: #16a34a;
}}

table {{
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
}}

th {{
    background: #111827;
    color: white;
    padding: 12px;
    text-align: left;
}}

td {{
    padding: 10px;
    border-bottom: 1px solid #e5e7eb;
}}

.footer {{
    margin-top: 30px;
    color: #6b7280;
    font-size: 13px;
}}

</style>

</head>

<body>

<div class="container">

<h1>
Network Intrusion Detection System
</h1>

<p class="subtitle">
Security Incident Report
</p>

<p>
<strong>Generated:</strong>
{report_time}
</p>

<div class="dashboard">

<div class="card">

<p>Total Alerts</p>

<h2>
{total_alerts}
</h2>

</div>

<div class="card">

<p>High Risk</p>

<h2 class="high">
{high_count}
</h2>

</div>

<div class="card">

<p>Medium Risk</p>

<h2 class="medium">
{medium_count}
</h2>

</div>

<div class="card">

<p>Low Risk</p>

<h2 class="low">
{low_count}
</h2>

</div>

</div>

<h2>
Detected Security Events
</h2>

<table>

<thead>

<tr>

<th>ID</th>

<th>Timestamp</th>

<th>Alert Type</th>

<th>Source IP</th>

<th>Risk</th>

<th>Details</th>

</tr>

</thead>

<tbody>

{rows}

</tbody>

</table>

<div class="footer">

<p>
Generated by Network Intrusion Detection System.
</p>

<p>
This report is intended for cybersecurity monitoring
and educational demonstration purposes.
</p>

</div>

</div>

</body>

</html>
"""

        filename = (
            "nids_report_"
            + datetime.now().strftime("%Y%m%d_%H%M%S")
            + ".html"
        )

        filepath = os.path.join(
            self.report_folder,
            filename
        )

        with open(
            filepath,
            "w",
            encoding="utf-8"
        ) as file:

            file.write(html)

        return filepath